export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS'
export const SIGN_OUT_SUCCESS = 'SIGN_OUT_SUCCESS'
export const GET_FAVOURITES_SUCCESS = 'GET_FAVOURITES_SUCCESS'
export const SET_USER_PHOTOURL = 'SET_USER_PHOTOURL'
